### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by freedom-zt** [Undrizzle/vue-nice-scrollbar#2]
Uncaught SyntaxError: Unexpected token import
npm run dev 正常没有报错， 但是浏览器访问报错

**Comment by freedom-zt** [comment]
know that this is why?

**Comment by Undrizzle** [comment]
具体不清楚，游览器无法识别import,babel转码了没

**Comment by lburcusel** [comment]
Can you, please, be little more specific ?

**Comment by strikermdd** [comment]
i had the same problem - i created a project using vue-cli webpack, stage-2 its configured, but gives me the error Uncaught SyntaxError: Unexpected token import. I don't see errors in terminal.

**Comment by cpfarher** [comment]
An alternative to avoid the problem is use in the following way (look at the import sentence):

`import vueNiceScrollbar from 'vue-nice-scrollbar/src/components/vue-nice-scrollbar'`

`  components: {
    vueNiceScrollbar
  },`
